name: Test

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "37 14 * * 6"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Fish
        uses: fish-shop/install-fish-shell@v2

      - uses: jdx/mise-action@v4

      - name: Run tests
        uses: fish-shop/run-fishtape-tests@v2
        with:
          patterns: tests/test_fish_jj_prompt.fish
