name: Test

on:
  push:
    branches: [main]
  pull_request:
  schedule:
    - cron: "37 14 * * 6"

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install Fish
        uses: fish-shop/install-fish-shell@v2

      - uses: jdx/mise-action@v4

      - name: Install Fishtape
        uses: fish-shop/install-plugin@v2
        with:
          plugin-manager: fisher
          plugins: jorgebucaran/fishtape

      - name: Run CI
        run: mise run ci
